services:

  database:
    image: postgres:14.1
    hostname: psot_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: jeronimo
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: psot_info
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./db/init/:/docker-entrypoint-initdb.d/
      - psot_db_persist:/var/lib/postgresql/data/
    networks:
      - psot_internal_backbone

  pgadmin:
    image: dpage/pgadmin4:latest
    depends_on:
      - database
    ports: 
      - 8088:80
    environment:
      PGADMIN_DEFAULT_EMAIL: "jeronimo@jeronimo.pt"
      PGADMIN_DEFAULT_PASSWORD: "password123"
    networks:
      - psot_internal_backbone

  aggregator:
    build: aggregator/
    networks:
      - psot_internal_backbone
    depends_on:
      - database

  ingest:
    build: ingest/
    networks:
      - psot_internal_backbone
    ports:
      - 8081:80
    depends_on:
      - database

  api:
    build: api/
    networks:
      - psot_internal_backbone
    environment:
      FLASK_APP: "/api/src/api"
    ports:
      - 8089:5000
    depends_on:
      - database
      - mqtt

  mqtt:
    image: eclipse-mosquitto
    hostname: psot_notifications
    networks:
      - psot_internal_backbone
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
    ports:
      - 1883:1883
      - 9001:9001

volumes:
  psot_db_persist:

networks:
  psot_internal_backbone: {}
