DROP TABLE IF EXISTS Scan CASCADE;
DROP TABLE IF EXISTS Place CASCADE;
DROP TABLE IF EXISTS Occupancy CASCADE;
DROP TABLE IF EXISTS AccessPoint CASCADE;
DROP TABLE IF EXISTS Client CASCADE;

CREATE TABLE Place (
	id INTEGER AUTO_INCREMENT PRIMARY KEY,
    name varchar(50) NOT NULL,
    capacity integer NOT NULL
);

CREATE TABLE Scan (
	id INTEGER AUTO_INCREMENT PRIMARY KEY,
    scanTime DATETIME,
    FOREIGN KEY (`placeId`) REFERENCES Place (`id`) ON DELETE CASCADE
);

CREATE TABLE Occupancy (
	id INTEGER AUTO_INCREMENT PRIMARY KEY,
    time DATETIME NOT NULL,
    occupancyLevel DOUBLE NOT NULL,
    FOREIGN KEY (`placeId`) REFERENCES Place (`id`) ON DELETE CASCADE
);

CREATE TABLE AccessPoint (
	id INTEGER AUTO_INCREMENT PRIMARY KEY,
    name varchar(50) NOT NULL,
    macAddress varchar(255) NOT NULL,
    numConnectClients integer NOT NULL,
    FOREIGN KEY (`scanId`) REFERENCES Scan (`id`) ON DELETE CASCADE
);

CREATE TABLE Client (
	id INTEGER AUTO_INCREMENT PRIMARY KEY,
    macAddress varchar(255) NOT NULL,
    FOREIGN KEY (`scanId`) REFERENCES Scan (`id`) ON DELETE CASCADE,
    FOREIGN KEY (`accessPointId`) REFERENCES AccessPoint (`id`) ON DELETE CASCADE
);
